import { CartBanner } from "@/components/CartBanner";
import { Dialog } from "@/components/Dialog";
import { SheetCart } from "@/components/SheetCart";
import { SideMenu } from "@/components/SideMenu";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Foods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        <AuthProvider>
          <CartBanner>{children}</CartBanner>
          <SideMenu />
          <SheetCart />
          <Dialog />
        </AuthProvider>
      </body>
    </html>
  );
}
