import { Dialog } from "@/components/Dialog";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { CartProvider } from "./contexts/cart";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CartProvider>{children}</CartProvider>
        <Dialog />
      </body>
    </html>
  );
}
